version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}-php
    build:
      context: ./.docker/app
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      APP_SECRET: ${APP_SECRET}
      APP_ENV: ${APP_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?serverVersion=13&charset=utf8
    volumes:
      - ./:/var/www/${PROJECT_NAME}
      - ./var/log/php:/var/www/${PROJECT_NAME}/var/log
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - work-network

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - work-network

  web:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:alpine
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - ./.docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - work-network

volumes:
  postgres-data:
    name: ${PROJECT_NAME}-postgres-data

networks:
  work-network:
    name: ${PROJECT_NAME}-network